### ISSUE TITLE
Disable CM4 internal WiFi antennas and use external antenna on Asiair Plus

### ISSUE THREAD

**Issue by joshumax** [open-astro/StellarMate#1]
The Asiair Plus contains both a high-gain external antenna and a small internal wifi antenna. Since we obviously want to use the external antenna for longer range, we need to set the ANT2 GPIO to high and the ANT1 GPIO to low. This can be done by adding the following snippet of code into `/boot/firmware/config.txt`

`dtparam=ant2`

The documentation should likely be updated to include this bit of information.

**Comment by joeytroy** [comment]
@joshumax thanks for the details I added it to the Wiki for compiling the kernel source code since this is for the ASIAIR Plus. Seems it would make the most sense there as you need to compile the kernel to get the USB ports to work for the RPi Compute Module 4.

https://github.com/open-astro/linux/wiki
